### ISSUE TITLE
4D data support

### ISSUE THREAD

**Issue by josejimenezluna** [bwinkel/cygrid#15]
Dear cygrid mantainers,

I'm seeking for an alternative to `scipy.interpolate.griddata` and I just stumbled upon this package. Currently I am working with somewhat large 3-D data arrays (_i.e._ as in cartesian x, y, z, value), but I have only seen examples in your documentation dealing with the 2D-scenario (_i.e._ x, y, value).

I was wondering if cygrid supports such an scenario, and if that were the case if you could point me to how to use the package towards that goal.

Many thanks in advance,

**Comment by bwinkel** [comment]
Thanks a lot for your question, @josejimenezluna. Yes, cygrid can work with 3D data. However, it is tailored to grid astronomical data on the sphere, just to make sure, that you are aware of that.

One of the [notebooks](https://github.com/bwinkel/cygrid/blob/master/notebooks/B01_OTF-map_exposure_calculator.ipynb) shows how to do 3D gridding (starting from cell 35). The [manual](https://bwinkel.github.io/cygrid/latest/user_manual.html#gridding-spectral-data) also has a brief section about it (it is kept brief, as there is really not much to it, compared to 2D gridding, just add another axis...). 

Does this help? Feel free to get back to me, if not!
