### ISSUE TITLE
healpix regrid notebook issue

### ISSUE THREAD

**Issue by telegraphic** [bwinkel/cygrid#17]
Hi there, 

I was trying to open the ` 03_regrid_from_healpix.ipynb` tutorial notebook, but jupyter is complaining:

```
File Load Error for 03_regrid_from_healpix.ipynb
Unreadable Notebook: /Users/dancpr/Data/install/py/cygrid/notebooks/03_regrid_from_healpix.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')
```

Not sure why, as all the other notebooks load fine.

FWIW, we are hoping to use cygrid to convert all-sky FITS images from radio data into healpix, e.g. converting this:
![image](https://user-images.githubusercontent.com/713251/118588858-d1276580-b7d1-11eb-96ca-026670c59d55.png)

to this:
![image](https://user-images.githubusercontent.com/713251/118588906-ec927080-b7d1-11eb-9b88-fea56ff7d2a2.png)

We noticed our simple nearest neighbour method introduced artifacts, so something like cygrid seems the way to go!

**Comment by bwinkel** [comment]
Thanks a lot for reporting this issue. There was a missing bracket in the file. Not sure how that was produced... It is fixed now on the master branch.

Regarding the re-gridding, you should check-out the [sightline gridder class](https://bwinkel.github.io/cygrid/latest/user_manual.html#sight-line-gridding), which was made with healpix in mind. You just need to feed in all the world coordinates of your HPX pixels and are done.

One drawback, though, is that resampling with cygrid has the price of a slightly lower angular resolution, as the underlying algorithm is based on convolution. If that is a showstopper for you, you may want to have a look at [`astropy-reproject`](https://reproject.readthedocs.io/en/stable/), which also support HPX. Keep in mind that cygrid is not primarily aimed at re-sampling but really at gridding (of more or less irregular data).

Feel free to get back to us, if you have more questions.

**Comment by telegraphic** [comment]
Thanks @bwinkel -- I can see the notebook now so closing this issue. And thanks for the healpix tips too, I'll check out astropy-reproject also!
