### ISSUE TITLE
Don't pin dependencies

### ISSUE THREAD

**Issue by cdeil** [bwinkel/cygrid#2]
I wanted to try out `cygrid`, but get this error:

```
$ pip install cygrid --user
Collecting cygrid
  Downloading cygrid-0.9.4.tar.gz (575kB)
    100% |████████████████████████████████| 583kB 755kB/s 
    Complete output from command python setup.py egg_info:
    Package astropy has version 1.2.dev15642
    Version 1.0 required.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/pip-build-fudv73g8/cygrid/
```

This is because you pin dependencies to exact versions in your setup.py (see [here](https://github.com/bwinkel/cygrid/blob/39eb701c996ef3d80d347770c212eb4b0e91e95e/setup.py#L19)):

```
dependencies = [['cython', '0.20.2'], ['numpy', '1.8'], ['astropy', '1.0']]
```

This is bad, it will prevent many users to install and use your package. Maybe they have another code that needs Astropy 1.1 or just don't want to install a separate environment with exactly these versions just to get `cygrid`.

Instead do something like in the example [here](https://github.com/gammapy/gammapy/blob/85a85406308d1a676397e84acbeb7dd74eb44ca4/setup.py#L103) and put e.g.

```
install_requires=[
      'numpy>=1.10',
      'astropy>=1.0',
    ],
```

**Comment by bwinkel** [comment]
Actually, I stumbled upon this issue myself. Couldn't figure out a solution previously. Thanks for pointing this out! Interestingly, it works with astropy=1.1, just not version codes that include something like 'dev###'. Anyway, I'll try to provide a patch later today.

**Comment by bwinkel** [comment]
Could you try again, please? I've uploaded a new version (0.9.5) to pypi. On my machine, it seems to work now.

**Comment by cdeil** [comment]
Issue is fixed. Thanks!
