### ISSUE TITLE
gcc 4.7+ needed

### ISSUE THREAD

**Issue by bs538** [bwinkel/cygrid#4]
Thanks for making this package available, looking forward to trying it.

Just a quick note regarding the installation: Both installation via pip and compilation from source fail when using an older gcc version than 4.7. This is simply because for gcc < 4.7 the flag for C++11 is "-std=c++0x" and not "-std=c++11" (e.g. http://stackoverflow.com/questions/14674597/cc1plus-error-unrecognized-command-line-option-std-c11-with-g). This is not very hard to track down, but maybe a note can be added to the installation instructions. Although gcc 4.7 has been around for quite a while, some systems (such as mine) still seem to have older versions as the default.

**Comment by bwinkel** [comment]
Thanks for the hint! Just to make sure, you don't want us to fix it but a note in the README would suffice? One could perhaps try to query the version of gcc in setup.py and change the linker option accordingly. However, this could be somewhat messy, because there are also compilers other than gcc.

**Comment by bs538** [comment]
Thanks for the quick response. After upgrading to gcc 4.7 the installation worked fine for me, so I think a hint in the README is perfectly sufficient. As you say, tayloring the flags just to accommodate old gcc versions seems like a bit of an overkill.
