### ISSUE TITLE
anaconda: binary incompatibility on cygrid support 

### ISSUE THREAD

**Issue by bwinkel** [bwinkel/cygrid#9]
I get a strange error on my existing Anaconda installation, after I installed the new 1.0.1 version of `cygrid` from `conda-forge`:

```python
import cygrid                                                           
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-f2e9d062c951> in <module>
----> 1 import cygrid

~/local/miniconda3new/lib/python3.6/site-packages/cygrid/__init__.py in <module>
     21 if not _ASTROPY_SETUP_:
     22     # For egg_info test builds to pass, put package imports here.
---> 23     from .cygrid import *
     24     from .healpix import *
     25     from .hphashtab import *

__init__.pxd in init cygrid.cygrid()

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

It may be related to some old compilers/c-libs being present in my site-packages, because it works if I do it in a pristine installation:

```bash
conda create -n cygrid-test-3.6 python=3.6 python cygrid --channel conda-forge
activate cygrid-test-3.6
python
import cygrid
```
(Likewise for Python 3.7)

Let's wait if other users run into the same trouble, before we pursue this issue further.

**Comment by DanielLenz** [comment]
Works fine for me, even on a non-pristine env.

**Comment by bwinkel** [comment]
Well, today we had this issue on another computer (MacOS), with a pristine Anaconda installation (and an existing Python environment). Seems, we need to find the cause of this, after all.

**Comment by bwinkel** [comment]
I _think_, I may have found a fix for this. In the [conda-forge recipe](https://github.com/bwinkel/cygrid-feedstock/blob/master/recipe/meta.yaml) I had `numpy >=1.11` in the host requirements. But this actually means, that conda-forge will use the newest `numpy` version, while the oldest possible (compatible) version is desired. Usually, newer versions are ensuring binary compatibility with older versions, but not vice versa. By not specifying the version in the recipe, conda-forge automatically uses `numpy 1.9 / 1.11` (as of today) depending on the OS; see https://conda-forge.org/docs/meta.html.

What happened here was, that I had `numpy 1.15.4` installed, but `cygrid` was build against `numpy 1.16`...

**Comment by bwinkel** [comment]
OK, this probably did the trick, as we could use it now without problems on both machines that were previously making trouble. Closing this.
